services:
  shelly:
    build:
      context: .
      args:
        SSH_PUB_KEY: ${SSH_PUB_KEY}
        SSH_USER: ${SSH_USER}
        SSH_PASSWORD: ${SSH_PASSWORD}
    image: nickthecook/shelly:latest
